### ISSUE TITLE
Nx 19.2.0: Project graph cache directory moved form `.nx/cache` to `.nx/workspace-data`

### ISSUE THREAD

**Issue by SvenPistre** [ts-arch/ts-arch#80]
Since Nx 19.2.0 the project graph cache directory moved from `.nx/cache` to `.nx/workspace-data`.
Here is the corresponding [commit](https://github.com/nrwl/nx/commit/5e39cb00194f01a17c007c101452e47a91b547db).

This (understandably) led to the following `ts-arch` complaint during our architecture tests:
```
Error: ENOENT: no such file or directory, open '/builds/REDACTED/.nx/cache/project-graph.json'
```

Currently, our workaround is to have a top-level `.env` file with the following contents
```bash
NX_PROJECT_GRAPH_CACHE_DIRECTORY=".nx/workspace-data/"
```
This works because `ts-arch` gets the graph cache directory from this environment variable [here](https://github.com/ts-arch/ts-arch/blob/main/src/common/extraction/extractNxGraph.ts#L20).

To support lower versions of Nx, it would probably be a good idea to first try fetching the `project-graph.json` from `.nx/cache` and if this fails, to fetch it from `.nx/workspace-data`.

**Comment by torfmaster** [comment]
Hi @SvenPistre,

thank you for your analysis. I think it is correct though I would reverse the logic: otherwise nx might receive outdated data in case of an upgrade (which is a very likely scenario for running the tests) as opposed to receiving incorrect data in case of an downgrade of nx (which is unlikely).
Hence I would
 
 - fetch the graph from  `nx/workspace-data`
 - if that fails: fetch the graph from `.nx/cache`
 - if that fails: give up

**Comment by SvenPistre** [comment]
Hi @torfmaster,

actually Jonas dug in and discovered the workaround, I just reported it here :)

Here is a PR that implements your suggestion:
https://github.com/ts-arch/ts-arch/pull/81
